
[{if $listitem->oxorder__oxpaymenttype->value == "sccp_financing"}]
	[{capture name="sRow"}][{$smarty.block.parent}][{/capture}]
	[{assign var="sRow" value=$smarty.capture.sRow}]
	[{if !$readonly}]
		[{capture name="sDeleteRow"}]<a href="Javascript:top.oxid.admin.deleteThis('[{$listitem->oxorder__oxid->value}]');" class="delete" id="del.[{$_cnt}]" [{include file="help.tpl" helpid=item_delete}]></a>[{/capture}]
		[{capture name="sCancelRow"}]<a href="Javascript:StornoThisArticle('[{$listitem->oxorder__oxid->value}]');" class="pause" id="pau.[{$_cnt}]" [{include file="help.tpl" helpid=item_storno}]></a>[{/capture}]
		[{assign var="sRow" value=$sRow|replace:$smarty.capture.sDeleteRow:''}]
		[{assign var="sRow" value=$sRow|replace:$smarty.capture.sCancelRow:''}]
	[{/if}]
	[{$sRow}]
[{else}]
	[{$smarty.block.parent}]
[{/if}]